export const dashboardRoleGuides = {
  STUDENT: {
    name: 'Student',
    summary: 'Find affordable learning support, agree on a schedule, pay safely, and measure your progress.',
    actions: [
      {
        title: 'Find the right tutor',
        description: 'Search approved tutors by name, subject, lesson, topic, level, location, price, rating, or teaching mode.',
        to: '/tutors',
        linkLabel: 'Search tutors',
      },
      {
        title: 'Choose a lesson or propose a schedule',
        description: 'Open a tutor profile to compare courses, lesson prices, availability, and highlighted calendar dates. You can also create a custom recurring schedule proposal.',
        to: '/tutors',
        linkLabel: 'Compare tutor offers',
      },
      {
        title: 'Manage schedule proposals',
        description: 'Review revisions, accept a tutor response, reject an unsuitable proposal, or send a counter-offer before lessons are booked.',
        to: '/schedule-proposals',
        linkLabel: 'Open proposals',
      },
      {
        title: 'Follow your bookings',
        description: 'Track tutor approval, join a prepared online room during its secure access window, follow learning progress, and report a serious booking problem when support is needed.',
        to: '/bookings',
        linkLabel: 'Open bookings',
      },
      {
        title: 'Complete learning payments',
        description: 'Pay eligible booking charges or course purchases through the professional payment simulation, then retain the transaction record and printable receipt.',
        to: '/payments',
        linkLabel: 'Open payments',
      },
      {
        title: 'Learn and measure improvement',
        description: 'Access paid courses in your learning library, complete lessons, take initial and final assessments, and confirm whether the recorded outcome reflects your progress.',
        to: '/learning',
        linkLabel: 'Open learning',
      },
      {
        title: 'Open your productivity report card',
        description: 'Print or save an Isomo-branded report card showing course completion, tutoring attendance, confirmed assessment growth, and tutor progress notes.',
        to: '/reports',
        linkLabel: 'Open report card',
      },
      {
        title: 'Communicate and review',
        description: 'Message tutors connected to your bookings and leave an eligible rating or review after completed learning.',
        to: '/messages',
        linkLabel: 'Open messages',
      },
    ],
    limits: [
      'Tutor contact, private lessons, and paid course content are available only through eligible bookings or purchases.',
      'Assessments must be completed by the student. A parent cannot submit answers or confirm outcomes on your behalf.',
      'Reviews are available only after an eligible completed learning activity and cannot be used to change payment or booking records.',
      'You can submit and track a dispute for your own eligible booking, but only an administrator can investigate and resolve the case.',
      'You cannot approve tutors, publish courses, resolve disputes, manage payouts, or view another learner\'s private records.',
    ],
    tip: 'Use the notification bell for unread proposal changes, booking updates, payment results, and assessment activity.',
  },
  PARENT: {
    name: 'Parent or guardian',
    summary: 'Arrange affordable tutoring, pay for linked learners, and monitor each student\'s learning journey.',
    actions: [
      {
        title: 'Link and view students',
        description: 'Link an existing student account, open each learner individually, and review the information available for that student.',
        to: '/parent-students',
        linkLabel: 'Manage linked students',
      },
      {
        title: 'Find suitable tutors',
        description: 'Compare approved tutors by lesson, topic, level, teaching mode, rating, and price before choosing support for a linked learner.',
        to: '/tutors',
        linkLabel: 'Search tutors',
      },
      {
        title: 'Arrange lesson schedules',
        description: 'Request an available lesson or create a recurring schedule proposal for a linked student, then monitor tutor revisions and decisions.',
        to: '/schedule-proposals',
        linkLabel: 'Open proposals',
      },
      {
        title: 'Complete learning payments',
        description: 'Pay simulated booking charges or course purchases for an eligible linked student and retain the generated transaction record and receipt.',
        to: '/payments',
        linkLabel: 'Open payments',
      },
      {
        title: 'Monitor learning progress',
        description: 'Open bookings and individual student records to follow lesson status, securely join a linked learner\'s online room, review progress, and track reported disputes.',
        to: '/bookings',
        linkLabel: 'Review bookings',
      },
      {
        title: 'Read family learning reports',
        description: 'Use comprehensive family reports to understand booking activity, completed support, assessment outcomes, and each learner\'s recorded improvement.',
        to: '/reports',
        linkLabel: 'Open family reports',
      },
      {
        title: 'Communicate with tutors',
        description: 'Message tutors involved in your linked students\' bookings when lesson coordination or clarification is needed.',
        to: '/messages',
        linkLabel: 'Open messages',
      },
    ],
    limits: [
      'You can only view, book, pay, and communicate for students formally linked to your account.',
      'Students complete their own assessments, outcome confirmations, and eligible reviews.',
      'A parent payment does not bypass tutor approval, booking requirements, or course eligibility.',
      'You can submit and track a dispute for a formally linked student\'s eligible booking, but only an administrator can investigate and resolve it.',
      'You cannot approve tutors, moderate courses or reviews, resolve disputes, access tutor earnings, or inspect unrelated students.',
    ],
    tip: 'Open a learner from Linked students when you need a student-specific view instead of the combined family dashboard.',
  },
  TUTOR: {
    name: 'Tutor',
    summary: 'Complete verification, publish structured learning, manage students, and track verified teaching impact.',
    actions: [
      {
        title: 'Complete your professional verification',
        description: 'Upload identity and qualification documents, download and sign the integrity agreement, declare teaching subjects and levels, and respond to administrator feedback.',
        to: '/tutor-documents',
        linkLabel: 'Open verification',
      },
      {
        title: 'Build courses in order',
        description: 'Use the teaching workspace hierarchy: teaching subjects, course details, curriculum, individual lessons, assessments, then final review and submission.',
        to: '/tutor-teaching',
        linkLabel: 'Open teaching workspace',
      },
      {
        title: 'Create learning assessments',
        description: 'Add initial and final assessments with descriptions, expected knowledge outcomes, and questions for a course lesson or eligible individual booking.',
        to: '/assessments',
        linkLabel: 'Open assessments',
      },
      {
        title: 'Negotiate recurring schedules',
        description: 'Review custom schedule proposals, accept workable times, reject unsuitable requests, or return a clear counter-offer. Accepted proposals never replace an already booked slot.',
        to: '/schedule-proposals',
        linkLabel: 'Manage proposals',
      },
      {
        title: 'Deliver and record tutoring',
        description: 'Accept or reject requests, prepare secure meeting rooms for confirmed online lessons, update progress, and record the learner\'s initial and final level.',
        to: '/bookings',
        linkLabel: 'Manage bookings',
      },
      {
        title: 'Communicate with learners',
        description: 'Use booking-linked messages for lesson coordination and watch notifications for unread requests, proposal revisions, payments, and student outcome responses.',
        to: '/messages',
        linkLabel: 'Open messages',
      },
      {
        title: 'Track earnings and reputation',
        description: 'Review paid teaching income, payout history, ratings, lesson feedback, and student-confirmed learning improvement.',
        to: '/tutor-earnings',
        linkLabel: 'Open earnings',
      },
      {
        title: 'Review student feedback',
        description: 'Read eligible course and lesson ratings attached to completed learning, and use verified feedback to improve your teaching offer.',
        to: '/reviews',
        linkLabel: 'Open reviews',
      },
    ],
    limits: [
      'Marketplace visibility and teaching operations remain restricted until required documents, agreement, subjects, and administrator approval are complete.',
      'Submitted and published course content is locked from silent changes. Wait for a decision or requested changes before editing.',
      'You cannot approve your own verification or course, alter student payments, or access another tutor\'s bookings, messages, learners, or earnings.',
      'Public impact figures use eligible assessment results and student-confirmed outcomes; they must not be invented or edited manually.',
    ],
    tip: 'Follow the numbered teaching workspace from left to right. The Review step shows exactly what remains before course submission.',
  },
  ADMIN: {
    name: 'Administrator',
    summary: 'Protect platform trust, moderate evidence, monitor affordable learning, and preserve an auditable record.',
    actions: [
      {
        title: 'Manage account access',
        description: 'Search user records and apply documented activation, deactivation, suspension, or restoration actions without deleting operational history.',
        to: '/admin/users',
        linkLabel: 'Manage users',
      },
      {
        title: 'Verify tutor applications',
        description: 'Review tutor identity, qualification documents, signed agreements, requested subjects, and education levels. Preview evidence before recording a decision.',
        to: '/admin/tutor-reviews',
        linkLabel: 'Review tutors',
      },
      {
        title: 'Moderate submitted courses',
        description: 'Preview formatted course details, curriculum lessons, videos, and assessment readiness before publishing, requesting changes, or rejecting with a clear reason.',
        to: '/admin/courses',
        linkLabel: 'Review courses',
      },
      {
        title: 'Moderate reported reviews',
        description: 'Compare the original review with the reported concern, then hide a violation, restore safe feedback, or dismiss an unsupported report without rewriting the author\'s words.',
        to: '/admin/reviews',
        linkLabel: 'Review reports',
      },
      {
        title: 'Investigate disputes',
        description: 'Open the complete dispute record and evidence before making a decision. Preserve the reason, reviewer, and decision history.',
        to: '/admin/disputes',
        linkLabel: 'Open disputes',
      },
      {
        title: 'Process tutor payouts',
        description: 'Review requested amounts, approve valid withdrawals, reject requests with a documented reason, and mark approved payouts paid without reopening completed records.',
        to: '/admin/payouts',
        linkLabel: 'Manage payouts',
      },
      {
        title: 'Monitor outcomes and affordability',
        description: 'Use visual and printable reports to review students helped, booking activity, learning improvement, course purchases, revenue, and platform health.',
        to: '/reports',
        linkLabel: 'Open reports',
      },
      {
        title: 'Review the audit trail',
        description: 'Search and export significant administrative and system actions when investigating changes or preparing accountability records.',
        to: '/admin/audit',
        linkLabel: 'Open audit trail',
      },
    ],
    limits: [
      'Verification, moderation, access, and dispute decisions must be based on visible evidence and include useful reasons when action is taken.',
      'Administrative access must not be used to disclose private documents, messages, payment details, or student information without an operational need.',
      'Private lesson schedules and schedule proposals belong to the tutor, learner, and linked parent; administrators monitor aggregate operations instead.',
      'Admins must not impersonate users or silently rewrite bookings, payments, reviews, assessment outcomes, or historical decisions.',
      'Account deletion is unavailable because operational records must be preserved; use the documented access-status actions instead.',
    ],
    tip: 'Use the dashboard queues for urgent work, reports for aggregate monitoring, and the audit trail when you need to verify who changed a record.',
  },
}
