export const API_ENDPOINTS = {
  health: '/health/',
  auth: {
    login: '/auth/login/',
    logout: '/auth/logout/',
    register: '/auth/register/',
    me: '/auth/me/',
    refresh: '/auth/refresh/',
  },
  tutors: {
    list: '/tutors/',
    detail: (id) => `/tutors/${id}/`,
    dashboard: '/tutors/dashboard/',
    checklist: '/tutors/setup/checklist/',
    completion: '/tutors/me/completion/',
    agreement: '/tutors/agreement/',
    agreementDownload: '/tutors/agreement/download/',
    documents: '/tutors/documents/',
    documentReview: (id) => `/tutors/verifications/documents/${id}/review/`,
    verifications: '/tutors/verifications/',
    verificationDecision: (id) => `/tutors/verifications/${id}/decide/`,
  },
  students: {
    list: '/students/',
    detail: (id) => `/students/${id}/`,
    bookings: '/students/bookings/',
  },
  parents: {
    dashboard: '/parents/dashboard/',
    profile: '/parents/me/',
    links: '/parents/students/',
  },
  notifications: {
    list: '/notifications/',
    unread: '/notifications/unread/',
    readAll: '/notifications/read-all/',
    readOne: (id) => `/notifications/${id}/read/`,
  },
  chats: {
    unread: '/chats/unread/',
    threads: '/chats/threads/',
    messages: (bookingId) => `/chats/bookings/${bookingId}/messages/`,
    markRead: (bookingId) => `/chats/bookings/${bookingId}/messages/read/`,
  },
  reviews: {
    eligible: '/reviews/eligible/',
    bookingList: '/reviews/',
    bookingCreate: '/reviews/create/',
    lessonList: '/reviews/lesson/',
    lessonCreate: '/reviews/lesson/create/',
  },
  assessments: {
    list: '/assessments/assessments/',
    create: '/assessments/assessments/create/',
    questionCreate: '/assessments/assessments/questions/create/',
    questions: (id) => `/assessments/assessments/${id}/questions/`,
    attempts: '/assessments/attempts/',
    attemptCreate: '/assessments/attempts/create/',
    confirmations: '/assessments/confirmations/',
    confirmationCreate: '/assessments/confirmations/create/',
    impact: '/assessments/impact/',
  },  bookings: {
    list: '/bookings/',
    create: '/bookings/create/',
    action: (id) => `/bookings/${id}/action/`,
    disputes: '/bookings/disputes/',
    disputeCreate: '/bookings/disputes/create/',
    disputeDecision: (id) => `/bookings/disputes/${id}/decide/`,
  },
  payments: {
    list: '/payments/bookings/',
    coursePurchases: '/payments/course-purchases/',
    coursePurchaseCreate: '/payments/course-purchases/create/',
    learningLibrary: '/payments/learning-library/',
    lessonProgress: '/payments/lesson-progress/',
    lessonProgressUpdate: '/payments/lesson-progress/update/',
    payouts: '/payments/payouts/',
    payoutRequest: '/payments/payouts/request/',
    payoutDecision: (id) => `/payments/payouts/${id}/decide/`,
    payoutHistory: (id) => `/payments/payouts/${id}/history/`,
    earnings: '/payments/earnings/',
  },
  catalog: {
    subjects: '/catalog/subjects/',
    tutorSubjects: '/catalog/tutor-subjects/',
    tutorSubjectDetail: (id) => `/catalog/tutor-subjects/${id}/`,
    myCourses: '/catalog/my-courses/',
    courseCreate: '/catalog/courses/create/',
    courseSubmit: (id) => `/catalog/courses/${id}/submit/`,
    courses: '/catalog/courses/',
    courseDetail: (id) => `/catalog/courses/${id}/`,
    lessons: (courseId) => `/catalog/courses/${courseId}/lessons/`,
    lessonDetail: (id) => `/catalog/lessons/${id}/`,
  },
  reports: {
    dashboard: '/analytics/dashboard/',
    admin: '/analytics/report/',
    mine: '/analytics/my-report/',
  },
}
