export const queryKeys = {
  admin: {
    all: ['admin'],
    dashboard: ['admin', 'dashboard'],
    disputes: ['admin', 'disputes'],
    dispute: (id) => ['admin', 'disputes', 'detail', id],
    auditEvents: (params = {}) => ['admin', 'audit-events', params],
    users: (params = {}) => ['admin', 'users', params],
    user: (id) => ['admin', 'users', 'detail', id],
    courses: (params = {}) => ['admin', 'course-moderation', params],
    course: (id) => ['admin', 'course-moderation', 'detail', id],
    reviewReports: (params = {}) => ['admin', 'review-moderation', params],
    reviewReport: (id) => ['admin', 'review-moderation', 'detail', id],
    tutorVerifications: (status) => (
      status ? ['admin', 'tutor-verifications', { status }] : ['admin', 'tutor-verifications']
    ),
  },
  assessments: {
    all: ['assessments'],
    list: ['assessments', 'list'],
    attempts: ['assessments', 'attempts'],
    confirmations: ['assessments', 'confirmations'],
  },
  bookings: {
    all: ['bookings'],
    tutors: ['bookings', 'tutors'],
    tutorDetail: (id) => ['bookings', 'tutors', id],
    proposals: ['bookings', 'schedule-proposals'],
    disputes: ['bookings', 'disputes'],
  },
  catalog: {
    all: ['catalog'],
    subjects: ['catalog', 'subjects'],
    tutorSubjects: ['catalog', 'tutor-subjects'],
    tutorCourses: ['catalog', 'tutor-courses'],
    courseLessons: (courseId) => ['catalog', 'tutor-courses', courseId, 'lessons'],
    publicCourses: (filters = {}) => ['catalog', 'public-courses', filters],
    publicCoursesRoot: ['catalog', 'public-courses'],
    publicCourse: (id) => ['catalog', 'public-courses', 'detail', id],
  },
  chats: {
    all: ['chats'],
    threads: ['chats', 'threads'],
    unread: ['chats', 'unread-count'],
    messages: (bookingId) => ['chats', 'messages', bookingId],
  },
  learning: {
    all: ['learning'],
    library: ['learning', 'library'],
    lessonProgress: ['learning', 'lesson-progress'],
    impact: ['learning', 'impact'],
  },
  notifications: {
    all: ['notifications'],
    list: (params = {}) => ['notifications', 'list', params],
    unread: ['notifications', 'unread-count'],
  },
  parents: {
    all: ['parents'],
    dashboard: ['parents', 'dashboard'],
    links: ['parents', 'links'],
    student: (id) => ['parents', 'students', id],
  },
  payments: {
    all: ['payments'],
    providers: ['payments', 'providers'],
    bookings: ['payments', 'booking-payments'],
    coursePurchases: ['payments', 'course-purchases'],
    transaction: (kind, id) => ['payments', 'transaction', kind, id],
    tutorEarnings: ['payments', 'tutor-earnings'],
    tutorPayouts: ['payments', 'tutor-payouts'],
  },
  reviews: {
    all: ['reviews'],
    eligible: ['reviews', 'eligible'],
    bookings: ['reviews', 'bookings'],
    lessons: ['reviews', 'lessons'],
  },
  tutors: {
    all: ['tutors'],
    publicList: (params = {}) => ['tutors', 'public', params],
    detail: (id) => ['tutors', 'detail', id],
    dashboard: ['tutors', 'dashboard'],
    checklist: ['tutors', 'checklist'],
    documents: ['tutors', 'documents'],
    agreement: ['tutors', 'agreement'],
  },
}
